apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    method: fromcode
    run: nginx
    another: label  
  name: nginx-yaml
spec:
  containers:
  - image: nginx
    name: nginx
